### ISSUE TITLE
跑分还可以，但是出来的mask会很奇怪，对于某些inp_size而言会出现重影

### ISSUE THREAD

**Issue by LWShowTime** [NiFangBaAGe/Explicit-Visual-Prompt#11]
比如这样：
![image](https://github.com/NiFangBaAGe/Explicit-Visual-Prompt/assets/51390653/79a8142c-e49a-45ca-b3b5-57d5cfabf72e)
感觉是高频处理的锅？

**Comment by LWShowTime** [comment]
已解决，issue提了。

**Comment by s10400015** [comment]
想請問一下高頻處理的部分我可以在哪份code找到

**Comment by Cococc2** [comment]
> 想請問一下高頻處理的部分我可以在哪份code找到

请问你找到了吗 我没找到T T

**Comment by s10400015** [comment]
> > 想請問一下高頻處理的部分我可以在哪份code找到
> 
> 请问你找到了吗 我没找到T T

我目前正在研究 Explicit-Visual-Prompt/models/mmseg/models/backbones/mix_transformer_evp.py 這份code裡面的
class PromptGenerator(nn.Module)
