### ISSUE TITLE
Model for SOD task

### ISSUE THREAD

**Issue by RickyYXY** [NiFangBaAGe/Explicit-Visual-Prompt#2]
In your paper you have mentioned your work can also solve the salient object detection task, but I can't find configs for this task.
Can you show me how to do SOD using your network?
Thks.

**Comment by NiFangBaAGe** [comment]
Thanks for your interest in our work.
Our method is also applicable to SOD. We have released the model [here](https://uofmacau-my.sharepoint.com/:f:/g/personal/mc05379_umac_mo/EneRfHlTuPZCjH-VVBZVQpMBFXqqdRdU6l8a31jo3i5GOA?e=zagGg1).
More details can be found in our latest manuscript [here](https://arxiv.org/abs/2305.18476). The codes and models will be released soon.

**Comment by LWShowTime** [comment]
> 

Hi, @RickyYXY Did you got the config file for SOD tasks?
Hi, @NiFangBaAGe  Can you please update the yaml file for Salient object detection?
