### ISSUE TITLE
no module found bug

### ISSUE THREAD

**Issue by LWShowTime** [NiFangBaAGe/Explicit-Visual-Prompt#8]
Lots of module in the mmseg have this bug.
![image](https://github.com/NiFangBaAGe/Explicit-Visual-Prompt/assets/51390653/a7727ff4-43c8-4ecb-989e-86a2e59df450)
As in the picture shows, the import mmseg failed. 
I need to change all the files one by one...

**Comment by LWShowTime** [comment]
Or should I `pip install mmseg`? Since I know there is a mmseg module inside the /models/ of your project and there is no mmseg requirements in your requirement file. So I tend to believe this is the bug of import path.

**Comment by NiFangBaAGe** [comment]
Thanks for your interest in our work.
mmseg is an external package. You can install it via ```pip install mmsegmentation```, and the version of my environment is 0.30.0.
